server:
  port: 8080

bath:
  path: http://localhost:8989

flowable:
  common:
    app:
      role-prefix:
      idm-url: ${bath.path}/idm
      idm-admin:
        user: admin
        password: test
        firstName: admin
        lastName: admin
  #关闭定时任务JOB
  async-executor-activate: false
  #  将databaseSchemaUpdate设置为true。当Flowable发现库与数据库表结构不一致时，会自动将数据库表结构升级至新版本。
  database-schema-update: true
  process:
    definitionCacheLimit: -1
  activityFontName: 宋体
  annotationFontName: 宋体
  labelFontName: 宋体
  xml:
    encoding: UTF-8


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flowabletest?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&nullCatalogMeansCurrent=true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 542846492
    type: com.alibaba.druid.pool.DruidDataSource


## Mybatis
mybatis:
  mapperLocations: classpath:/mapper/*.xml
  configLocation: classpath:/META-INF/mybatis-config.xml
  configurationProperties:
    blobType: BLOB
    boolValue: TRUE
    prefix:
